[package]
name = "tf"
version = "0.1.0"
edition = "2021"

[lib]
name = "tf"
crate-type = ["cdylib"]

[dependencies]
winapi = { version = "0.3.9" }
detour = { version = "0.8.1" }
shared = { path = "../shared" }
game = { path = "../game" }
